### ISSUE TITLE
Error `std::invalid_argument` from LG when mixing XOR and PB constraints

### ISSUE THREAD

**Issue by vuphan314** [zzwonder/DPMaxSAT#2]
@zzwonder
In this [instance](https://github.com/zzwonder/DPMaxSAT/blob/d2e07af683fee6f8e8d87a2f7c01ad18cb0c66d5/examples/pbtest.wbo), the last constraint is XOR.
LG appears to mishandle mixed XOR and PB constraints.

From dir `lg/`:
```bash
build/lg "./solvers/flow-cutter-pace17/flow_cutter_pace17 -p 100" < ../examples/pbtest.wbo
```

Output:
```
c pid 402250
c num clauses = 7
c number of variables 7
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

**Comment by zzwonder** [comment]
Thanks @vuphan314 for pointing it out. XOR constraints are not supposed to appear in the WBO format. I removed the XOR constraint in that example. To have both XOR and PB in a hybrid MaxSAT instance, check this [example](https://github.com/zzwonder/DPMaxSAT/blob/9141ec0e4af20ed7ccfea7bc5d6f4f7e14130324/examples/hybrid.hwcnf)

**Comment by vuphan314** [comment]
Thanks for clarifying that XOR works with the HWCNF format but not WBO. This issue is then resolved.
