### ISSUE TITLE
Duplicate files `logic.cc`

### ISSUE THREAD

**Issue by vuphan314** [zzwonder/DPMaxSAT#3]
@zzwonder Which of these `logic.cc` files should be kept?
1. [addmc/src/](https://github.com/zzwonder/DPMaxSAT/blob/92d4f33d6a68d09cf07494a5026374a3472c6a27/addmc/src/logic.cc)
2. [dmc/](https://github.com/zzwonder/DPMaxSAT/blob/92d4f33d6a68d09cf07494a5026374a3472c6a27/dmc/logic.cc)

**Comment by zzwonder** [comment]
The one in addmc/src/ should be kept. I will delete the one in dmc/

**Comment by vuphan314** [comment]
Thanks. A duplicate was deleted in https://github.com/zzwonder/DPMaxSAT/commit/f93cd95e6ad0e55817b4617f96ca59ea515c6a02.
