### ISSUE TITLE
Duplicate examples

### ISSUE THREAD

**Issue by vuphan314** [zzwonder/DPMaxSAT#5]
These files have the same content:
https://github.com/zzwonder/DPMaxSAT/blob/b4c68fd6eec27ff40ed191c32e86a31ab35ef5a3/examples/cnfxor.cnf
https://github.com/zzwonder/DPMaxSAT/blob/b4c68fd6eec27ff40ed191c32e86a31ab35ef5a3/examples/cnfxor50.cnf

**Comment by zzwonder** [comment]
Thanks for pointing it out, deleted.

**Comment by vuphan314** [comment]
Thanks. Duplicate deleted in https://github.com/zzwonder/DPMaxSAT/commit/c6dc5c931a95fc27f3efb49583fb6c8e0e50d780
